"""empty message

Revision ID: 2238c1ef3f0b
Revises: 
Create Date: 2024-10-16 15:04:33.964254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2238c1ef3f0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('montadoras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('ano_fundacao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_montadoras_id'), 'montadoras', ['id'], unique=False)
    op.create_index(op.f('ix_montadoras_nome'), 'montadoras', ['nome'], unique=False)
    op.create_table('modelos_veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('montadora_id', sa.Integer(), nullable=True),
    sa.Column('valor_referencia', sa.Float(), nullable=True),
    sa.Column('motorizacao', sa.Integer(), nullable=True),
    sa.Column('turbo', sa.Boolean(), nullable=True),
    sa.Column('automatico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['montadora_id'], ['montadoras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_veiculos_id'), 'modelos_veiculos', ['id'], unique=False)
    op.create_index(op.f('ix_modelos_veiculos_nome'), 'modelos_veiculos', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelos_veiculos_nome'), table_name='modelos_veiculos')
    op.drop_index(op.f('ix_modelos_veiculos_id'), table_name='modelos_veiculos')
    op.drop_table('modelos_veiculos')
    op.drop_index(op.f('ix_montadoras_nome'), table_name='montadoras')
    op.drop_index(op.f('ix_montadoras_id'), table_name='montadoras')
    op.drop_table('montadoras')
    # ### end Alembic commands ###
