"""empty message

Revision ID: 57f09daaf29c
Revises: 2238c1ef3f0b
Create Date: 2024-10-16 17:29:50.638483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f09daaf29c'
down_revision: Union[str, None] = '2238c1ef3f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('montadora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('ano_fundacao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_montadora_id'), 'montadora', ['id'], unique=False)
    op.create_index(op.f('ix_montadora_nome'), 'montadora', ['nome'], unique=False)
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('montadora_id', sa.Integer(), nullable=True),
    sa.Column('valor_referencia', sa.Float(), nullable=True),
    sa.Column('motorizacao', sa.Integer(), nullable=True),
    sa.Column('turbo', sa.Boolean(), nullable=True),
    sa.Column('automatico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['montadora_id'], ['montadora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelo_id'), 'modelo', ['id'], unique=False)
    op.create_index(op.f('ix_modelo_nome'), 'modelo', ['nome'], unique=False)
    op.drop_index('ix_modelos_veiculos_id', table_name='modelos_veiculos')
    op.drop_index('ix_modelos_veiculos_nome', table_name='modelos_veiculos')
    op.drop_table('modelos_veiculos')
    op.drop_index('ix_montadoras_id', table_name='montadoras')
    op.drop_index('ix_montadoras_nome', table_name='montadoras')
    op.drop_table('montadoras')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('montadoras',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('montadoras_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pais', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ano_fundacao', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='montadoras_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_montadoras_nome', 'montadoras', ['nome'], unique=False)
    op.create_index('ix_montadoras_id', 'montadoras', ['id'], unique=False)
    op.create_table('modelos_veiculos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('montadora_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_referencia', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('motorizacao', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('turbo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('automatico', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['montadora_id'], ['montadoras.id'], name='modelos_veiculos_montadora_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='modelos_veiculos_pkey')
    )
    op.create_index('ix_modelos_veiculos_nome', 'modelos_veiculos', ['nome'], unique=False)
    op.create_index('ix_modelos_veiculos_id', 'modelos_veiculos', ['id'], unique=False)
    op.drop_index(op.f('ix_modelo_nome'), table_name='modelo')
    op.drop_index(op.f('ix_modelo_id'), table_name='modelo')
    op.drop_table('modelo')
    op.drop_index(op.f('ix_montadora_nome'), table_name='montadora')
    op.drop_index(op.f('ix_montadora_id'), table_name='montadora')
    op.drop_table('montadora')
    # ### end Alembic commands ###
