"""empty message

Revision ID: eddba5dbcd5d
Revises: 
Create Date: 2024-10-17 16:28:14.427733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eddba5dbcd5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('montadora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('ano_fundacao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_montadora_id'), 'montadora', ['id'], unique=False)
    op.create_index(op.f('ix_montadora_nome'), 'montadora', ['nome'], unique=False)
    op.create_table('modelo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('montadora_id', sa.Integer(), nullable=True),
    sa.Column('valor_referencia', sa.Float(), nullable=True),
    sa.Column('motorizacao', sa.Integer(), nullable=True),
    sa.Column('turbo', sa.Boolean(), nullable=True),
    sa.Column('automatico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['montadora_id'], ['montadora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelo_id'), 'modelo', ['id'], unique=False)
    op.create_index(op.f('ix_modelo_nome'), 'modelo', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelo_nome'), table_name='modelo')
    op.drop_index(op.f('ix_modelo_id'), table_name='modelo')
    op.drop_table('modelo')
    op.drop_index(op.f('ix_montadora_nome'), table_name='montadora')
    op.drop_index(op.f('ix_montadora_id'), table_name='montadora')
    op.drop_table('montadora')
    # ### end Alembic commands ###
